package com.example.lab1swdev.mybatis.dao;

import com.example.lab1swdev.mybatis.model.Electivecourse;
import java.util.List;

public interface ElectivecourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ELECTIVECOURSE
     *
     * @mbg.generated Tue Mar 11 15:10:33 EET 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ELECTIVECOURSE
     *
     * @mbg.generated Tue Mar 11 15:10:33 EET 2025
     */
    int insert(Electivecourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ELECTIVECOURSE
     *
     * @mbg.generated Tue Mar 11 15:10:33 EET 2025
     */
    Electivecourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ELECTIVECOURSE
     *
     * @mbg.generated Tue Mar 11 15:10:33 EET 2025
     */
    List<Electivecourse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ELECTIVECOURSE
     *
     * @mbg.generated Tue Mar 11 15:10:33 EET 2025
     */
    int updateByPrimaryKey(Electivecourse record);
}