package com.example.lab1swdev.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.LASTNAME
     *
     * @return the value of PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.LASTNAME
     *
     * @param lastname the value for PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @return the value of PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @param groupId the value for PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sat Mar 08 16:02:29 EET 2025
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}